Add math library to dependencies
On Fedora 30 currently, iwlib does not build (using gcc9) because the -lm flag is missing.

iwlib uses floor and pow, and since no `.pc` file is given, I have "undefined references" galore. Maybe this is an upstream bug because `ldd /usr/lib64/libiw.so` lacks libm, but at least this patch makes `cabal new-install iwlib` work.

Below, the relevant output of ` LANG=C cabal new-install iwlib -j1 -v3 --package-env default --lib`
```
Configuration files installed in:
/home/gagbo/.cabal/store/ghc-8.6.3/iwlib-0.1.0-70ce4a68d4bc31abc35140e7690c588032fa765a01f8c58335ea11740e5908db/etc
Using alex version 3.2.4 found on system at: /usr/bin/alex
Using ar found on system at: /usr/bin/ar
Using c2hs version 0.28.6 found on system at: /home/gagbo/.cabal/bin/c2hs
No cpphs found
No doctest found
Using gcc version 9 found on system at: /usr/bin/gcc
Using ghc version 8.6.3 given by user at: /usr/bin/ghc
Using ghc-pkg version 8.6.3 given by user at: /usr/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.22.0 found on system at: /usr/bin/haddock
Using happy version 1.19.9 found on system at: /usr/bin/happy
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at: /usr/bin/hpc
Using hsc2hs version 0.68.5 found on system at: /usr/bin/hsc2hs
No hscolour found
No jhc found
Using ld found on system at: /usr/bin/ld.gold
Using pkg-config version 1.6.0 found on system at: /usr/bin/pkg-config
Using runghc version 8.6.3 found on system at: /usr/bin/runghc
Using strip version 2.31 found on system at: /usr/bin/strip
Using tar found on system at: /usr/bin/tar
No uhc found
/usr/bin/gcc -fno-stack-protector '-fuse-ld=gold' /tmp/17116-11.c -o /tmp/17116-12 '-D__GLASGOW_HASKELL__=806' '-Dlinux_BUILD_OS=1' '-Dx86_64_BUILD_ARCH=1' '-Dlinux_HOST_OS=1' '-Dx86_64_HOST_ARCH=1' -Idist/build/autogen -I. -I/usr/lib64/ghc-8.6.3/base-4.12.0.0/include -I/usr/lib64/ghc-8.6.3/integer-gmp-1.0.2.0/include -I/usr/lib64/ghc-8.6.3/include -liw -L/usr/lib64/ghc-8.6.3/base-4.12.0.0 -L/usr/lib64/ghc-8.6.3/integer-gmp-1.0.2.0 -L/usr/lib64/ghc-8.6.3/ghc-prim-0.5.3 -L/usr/lib64/ghc-8.6.3/rts
/usr/bin/gcc returned ExitFailure 1 with error message:
/usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libiw.so: error:
undefined reference to 'floor'
/usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libiw.so: error:
undefined reference to 'pow'
/usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libiw.so: error:
undefined reference to 'log10'
collect2: error: ld returned 1 exit status
/usr/bin/gcc -fno-stack-protector '-fuse-ld=gold' /tmp/17116-13.c -o /tmp/17116-14 -liw -L/usr/lib64/ghc-8.6.3/base-4.12.0.0 -L/usr/lib64/ghc-8.6.3/integer-gmp-1.0.2.0 -L/usr/lib64/ghc-8.6.3/ghc-prim-0.5.3 -L/usr/lib64/ghc-8.6.3/rts
/usr/bin/gcc returned ExitFailure 1 with error message:
/usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libiw.so: error:
undefined reference to 'floor'
/usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libiw.so: error:
undefined reference to 'pow'
/usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libiw.so: error:
undefined reference to 'log10'
collect2: error: ld returned 1 exit status
/usr/bin/gcc -fno-stack-protector '-fuse-ld=gold' /tmp/17116-15.c -o /tmp/17116-16 -liw -L/usr/lib64/ghc-8.6.3/base-4.12.0.0 -L/usr/lib64/ghc-8.6.3/integer-gmp-1.0.2.0 -L/usr/lib64/ghc-8.6.3/ghc-prim-0.5.3 -L/usr/lib64/ghc-8.6.3/rts
/usr/bin/gcc returned ExitFailure 1 with error message:
/usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libiw.so: error:
undefined reference to 'floor'
/usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libiw.so: error:
undefined reference to 'pow'
/usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libiw.so: error:
undefined reference to 'log10'
collect2: error: ld returned 1 exit status
/usr/bin/gcc -fno-stack-protector '-fuse-ld=gold' /tmp/17116-17.c -o /tmp/17116-18 -c '-D__GLASGOW_HASKELL__=806' '-Dlinux_BUILD_OS=1' '-Dx86_64_BUILD_ARCH=1' '-Dlinux_HOST_OS=1' '-Dx86_64_HOST_ARCH=1' -Idist/build/autogen -I. -I/usr/lib64/ghc-8.6.3/base-4.12.0.0/include -I/usr/lib64/ghc-8.6.3/integer-gmp-1.0.2.0/include -I/usr/lib64/ghc-8.6.3/include
CallStack (from HasCallStack):
  die', called at ./Distribution/Simple/Configure.hs:1804:34 in Cabal-2.4.1.0-LMNYbebe1EM6PPXcRCtlkv:Distribution.Simple.Configure
  checkForeignDeps, called at ./Distribution/Simple.hs:615:7 in Cabal-2.4.1.0-LMNYbebe1EM6PPXcRCtlkv:Distribution.Simple
cabal: Missing dependency on a foreign library:
* Missing (or bad) C library: iw
```

Also
```
ldd /usr/lib64/libiw.so
        linux-vdso.so.1 (0x00007ffd8179a000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2b430e2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2b432eb000)
```
and to be complete `wireless-tools-devel-29-22.fc30.x86_64`